import { PrismaClient, PropertySource, PropertyType } from '@prisma/client';

const prisma = new PrismaClient();

const ZAGREB_LISTINGS = [
  {
    externalId: 'nj-001',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-001',
    title: 'Prodaja stana, Gornji Grad, 65m²',
    description: 'Lijepo renoviran stan u centru Zagreba, 3. kat, lift, parking.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Gornji Grad',
    address: 'Ilica 10',
    price: 185000,
    area: 65,
    pricePerM2: 2846,
    rooms: 3,
    floor: 3,
    totalFloors: 5,
    yearBuilt: 1970,
    isNewBuild: false,
    condition: 'renovirano',
    hasParking: true,
    hasBalcony: false,
    hasElevator: true,
    images: ['https://example.com/img/001a.jpg', 'https://example.com/img/001b.jpg'],
  },
  {
    externalId: 'nj-002',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-002',
    title: 'Novogradnja, Špansko, 55m²',
    description: 'Novogradnja u mirnom kvartu, odlična infrastruktura, garaža.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Špansko',
    address: 'Špansko bb',
    price: 160000,
    area: 55,
    pricePerM2: 2909,
    rooms: 2,
    floor: 2,
    totalFloors: 6,
    yearBuilt: 2024,
    isNewBuild: true,
    condition: 'novo',
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    images: ['https://example.com/img/002a.jpg'],
  },
  {
    externalId: 'nj-003',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-003',
    title: 'Stan, Maksimir, 80m², 4-sobni',
    description: 'Prostran stan blizu parka Maksimir, odlična lokacija za obitelji.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Maksimir',
    address: 'Maksimirska 50',
    price: 220000,
    area: 80,
    pricePerM2: 2750,
    rooms: 4,
    floor: 1,
    totalFloors: 4,
    yearBuilt: 1985,
    isNewBuild: false,
    condition: 'za renovaciju',
    hasParking: false,
    hasBalcony: true,
    hasElevator: false,
    images: ['https://example.com/img/003a.jpg'],
  },
  {
    externalId: 'nj-004',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-004',
    title: 'Garsonijera, Trnje, 30m²',
    description: 'Moderno opremljena garsonijera, blizu tramvaja.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Trnje',
    address: 'Heinzelova 5',
    price: 95000,
    area: 30,
    pricePerM2: 3166,
    rooms: 1,
    floor: 4,
    totalFloors: 8,
    yearBuilt: 2010,
    isNewBuild: false,
    condition: 'novo',
    hasParking: false,
    hasBalcony: false,
    hasElevator: true,
    images: ['https://example.com/img/004a.jpg', 'https://example.com/img/004b.jpg'],
  },
  {
    externalId: 'nj-005',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/kuca-005',
    title: 'Kuća, Sesvete, 150m², okućnica 400m²',
    description: 'Samostojeća kuća s vrtom, garažom i podrumom.',
    propertyType: PropertyType.HOUSE,
    city: 'Zagreb',
    neighborhood: 'Sesvete',
    address: 'Sesvetska cesta 20',
    price: 350000,
    area: 150,
    pricePerM2: 2333,
    rooms: 5,
    floor: null,
    totalFloors: 2,
    yearBuilt: 2000,
    isNewBuild: false,
    condition: 'renovirano',
    hasParking: true,
    hasBalcony: true,
    hasElevator: false,
    images: ['https://example.com/img/005a.jpg', 'https://example.com/img/005b.jpg'],
  },
  {
    externalId: 'nj-006',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-006',
    title: 'Stan, Črnomerec, 72m²',
    description: 'Lijepo uređen stan, blizu tramvajske linije 6.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Črnomerec',
    address: 'Črnomerec 15',
    price: 195000,
    area: 72,
    pricePerM2: 2708,
    rooms: 3,
    floor: 2,
    totalFloors: 5,
    yearBuilt: 1978,
    isNewBuild: false,
    condition: 'renovirano',
    hasParking: true,
    hasBalcony: true,
    hasElevator: false,
    images: ['https://example.com/img/006a.jpg'],
  },
  {
    externalId: 'nj-007',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-007',
    title: 'Penthouse, Srebrnjak, 120m²',
    description: 'Luksuzni penthouse s terasom i panoramskim pogledom.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Srebrnjak',
    address: 'Srebrnjak 30',
    price: 480000,
    area: 120,
    pricePerM2: 4000,
    rooms: 4,
    floor: 8,
    totalFloors: 8,
    yearBuilt: 2018,
    isNewBuild: false,
    condition: 'novo',
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    images: ['https://example.com/img/007a.jpg', 'https://example.com/img/007b.jpg'],
  },
  {
    externalId: 'nj-008',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-008',
    title: 'Stan, Novi Zagreb, 58m²',
    description: 'Funkcionalan stan u Novom Zagrebu, blizu Bundeka.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Novi Zagreb',
    address: 'Večernjakova 8',
    price: 140000,
    area: 58,
    pricePerM2: 2413,
    rooms: 2,
    floor: 5,
    totalFloors: 10,
    yearBuilt: 1990,
    isNewBuild: false,
    condition: 'za renovaciju',
    hasParking: false,
    hasBalcony: true,
    hasElevator: true,
    images: ['https://example.com/img/008a.jpg'],
  },
  {
    externalId: 'nj-009',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-009',
    title: 'Novogradnja, Prečko, 61m², 2-sobni',
    description: 'Novogradnja u fazi završetka, useljivo Q3 2025.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Prečko',
    address: 'Prečkova 12',
    price: 175000,
    area: 61,
    pricePerM2: 2868,
    rooms: 2,
    floor: 3,
    totalFloors: 7,
    yearBuilt: 2025,
    isNewBuild: true,
    condition: 'novo',
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    images: ['https://example.com/img/009a.jpg'],
  },
  {
    externalId: 'nj-010',
    source: PropertySource.NJUSKALO,
    sourceUrl: 'https://www.njuskalo.hr/nekretnine/stan-010',
    title: 'Dvosoban stan, Jarun, 50m²',
    description: 'Ugodan dvosoban stan 200m od jezera Jarun.',
    propertyType: PropertyType.APARTMENT,
    city: 'Zagreb',
    neighborhood: 'Jarun',
    address: 'Jankomir 4',
    price: 148000,
    area: 50,
    pricePerM2: 2960,
    rooms: 2,
    floor: 1,
    totalFloors: 3,
    yearBuilt: 1995,
    isNewBuild: false,
    condition: 'renovirano',
    hasParking: false,
    hasBalcony: false,
    hasElevator: false,
    images: ['https://example.com/img/010a.jpg'],
  },
];

async function main() {
  console.log('Seeding database with Zagreb listings...');

  for (const listing of ZAGREB_LISTINGS) {
    await prisma.property.upsert({
      where: { externalId: listing.externalId },
      update: { lastSeenAt: new Date() },
      create: listing,
    });
  }

  console.log(`Seeded ${ZAGREB_LISTINGS.length} properties.`);
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
